-- =============================================
-- 增加更多培训课程
-- =============================================

-- 课程1：AI人工智能实战
INSERT INTO TRAINING_COURSES (COURSE_ID, COURSE_NAME, COURSE_TYPE, DURATION, TRAINER_ID, MAX_STUDENTS, 
    START_TIME, END_TIME, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID, CREATED_DATE) 
VALUES (SEQ_COURSE.NEXTVAL, 'AI人工智能实战训练营', '技能类', 24, 1, 25,
    TO_DATE('2026-06-01 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-06-03 17:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    '培训中心301', '发布', 35000, 1, SYSDATE);

-- 课程2：高效沟通与团队协作
INSERT INTO TRAINING_COURSES (COURSE_ID, COURSE_NAME, COURSE_TYPE, DURATION, TRAINER_ID, MAX_STUDENTS, 
    START_TIME, END_TIME, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID, CREATED_DATE) 
VALUES (SEQ_COURSE.NEXTVAL, '高效沟通与团队协作', '管理类', 8, 2, 30,
    TO_DATE('2026-06-05 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-06-05 17:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    '培训中心102', '发布', 12000, 2, SYSDATE);

-- 课程3：数据可视化分析
INSERT INTO TRAINING_COURSES (COURSE_ID, COURSE_NAME, COURSE_TYPE, DURATION, TRAINER_ID, MAX_STUDENTS, 
    START_TIME, END_TIME, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID, CREATED_DATE) 
VALUES (SEQ_COURSE.NEXTVAL, '数据可视化分析（Tableau/Power BI）', '技能类', 12, 3, 20,
    TO_DATE('2026-06-08 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-06-09 17:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    '培训中心203', '发布', 18000, 1, SYSDATE);

-- 课程4：项目管理实战
INSERT INTO TRAINING_COURSES (COURSE_ID, COURSE_NAME, COURSE_TYPE, DURATION, TRAINER_ID, MAX_STUDENTS, 
    START_TIME, END_TIME, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID, CREATED_DATE) 
VALUES (SEQ_COURSE.NEXTVAL, '项目管理实战（PMP方向）', '管理类', 16, 1, 25,
    TO_DATE('2026-06-12 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-06-14 17:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    '培训中心301', '发布', 28000, 3, SYSDATE);

-- 课程5：Excel高级数据处理
INSERT INTO TRAINING_COURSES (COURSE_ID, COURSE_NAME, COURSE_TYPE, DURATION, TRAINER_ID, MAX_STUDENTS, 
    START_TIME, END_TIME, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID, CREATED_DATE) 
VALUES (SEQ_COURSE.NEXTVAL, 'Excel高级数据处理与自动化', '技能类', 6, 2, 35,
    TO_DATE('2026-06-15 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-06-15 17:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    '培训中心101', '发布', 8000, 4, SYSDATE);

-- 课程6：领导力与战略思维
INSERT INTO TRAINING_COURSES (COURSE_ID, COURSE_NAME, COURSE_TYPE, DURATION, TRAINER_ID, MAX_STUDENTS, 
    START_TIME, END_TIME, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID, CREATED_DATE) 
VALUES (SEQ_COURSE.NEXTVAL, '领导力与战略思维', '管理类', 12, 1, 20,
    TO_DATE('2026-06-18 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-06-19 17:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    '培训中心302', '发布', 30000, 2, SYSDATE);

-- 课程7：云计算基础与实战
INSERT INTO TRAINING_COURSES (COURSE_ID, COURSE_NAME, COURSE_TYPE, DURATION, TRAINER_ID, MAX_STUDENTS, 
    START_TIME, END_TIME, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID, CREATED_DATE) 
VALUES (SEQ_COURSE.NEXTVAL, '云计算基础与实战（AWS/阿里云）', '技能类', 20, 3, 15,
    TO_DATE('2026-06-22 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-06-24 17:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    '培训中心303', '发布', 40000, 1, SYSDATE);

-- 课程8：新员工入职培训
INSERT INTO TRAINING_COURSES (COURSE_ID, COURSE_NAME, COURSE_TYPE, DURATION, TRAINER_ID, MAX_STUDENTS, 
    START_TIME, END_TIME, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID, CREATED_DATE) 
VALUES (SEQ_COURSE.NEXTVAL, '新员工入职培训（企业文化与制度）', '管理类', 4, 2, 40,
    TO_DATE('2026-06-25 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-06-25 12:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    '培训中心101', '发布', 5000, 3, SYSDATE);

-- 课程9：网络安全与数据保护
INSERT INTO TRAINING_COURSES (COURSE_ID, COURSE_NAME, COURSE_TYPE, DURATION, TRAINER_ID, MAX_STUDENTS, 
    START_TIME, END_TIME, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID, CREATED_DATE) 
VALUES (SEQ_COURSE.NEXTVAL, '网络安全与数据保护', '技能类', 10, 1, 25,
    TO_DATE('2026-06-28 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-06-29 17:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    '培训中心202', '发布', 22000, 1, SYSDATE);

-- 课程10：跨文化沟通与国际商务
INSERT INTO TRAINING_COURSES (COURSE_ID, COURSE_NAME, COURSE_TYPE, DURATION, TRAINER_ID, MAX_STUDENTS, 
    START_TIME, END_TIME, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID, CREATED_DATE) 
VALUES (SEQ_COURSE.NEXTVAL, '跨文化沟通与国际商务礼仪', '管理类', 6, 1, 20,
    TO_DATE('2026-07-02 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-07-02 17:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    '培训中心201', '发布', 15000, 2, SYSDATE);

-- 课程11：敏捷开发与Scrum
INSERT INTO TRAINING_COURSES (COURSE_ID, COURSE_NAME, COURSE_TYPE, DURATION, TRAINER_ID, MAX_STUDENTS, 
    START_TIME, END_TIME, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID, CREATED_DATE) 
VALUES (SEQ_COURSE.NEXTVAL, '敏捷开发与Scrum实战', '技能类', 14, 3, 20,
    TO_DATE('2026-07-05 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-07-06 17:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    '培训中心203', '发布', 25000, 1, SYSDATE);

-- 课程12：情绪管理与压力疏导
INSERT INTO TRAINING_COURSES (COURSE_ID, COURSE_NAME, COURSE_TYPE, DURATION, TRAINER_ID, MAX_STUDENTS, 
    START_TIME, END_TIME, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID, CREATED_DATE) 
VALUES (SEQ_COURSE.NEXTVAL, '情绪管理与压力疏导', '管理类', 4, 2, 30,
    TO_DATE('2026-07-08 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-07-08 17:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    '培训中心102', '发布', 6000, 3, SYSDATE);

COMMIT;

-- 验证插入结果
SELECT COUNT(*) AS TOTAL_COURSES FROM TRAINING_COURSES WHERE COURSE_STATUS = '发布';

-- 查看所有课程
SELECT COURSE_ID, COURSE_NAME, COURSE_TYPE, DURATION, 
       TO_CHAR(START_TIME, 'YYYY-MM-DD HH24:MI') AS START_TIME,
       LOCATION, MAX_STUDENTS
FROM TRAINING_COURSES 
WHERE COURSE_STATUS = '发布'
ORDER BY START_TIME;