-- =============================================
-- 增加更多员工数据
-- =============================================

-- 插入更多部门预算数据（如果需要更多部门）
INSERT INTO DEPARTMENTS_TRAINING (DEPT_ID, DEPT_NAME, ANNUAL_BUDGET, USED_BUDGET, REMAIN_BUDGET) 
VALUES (SEQ_DEPT_TRAIN.NEXTVAL, '产品部', 90000, 0, 90000);

INSERT INTO DEPARTMENTS_TRAINING (DEPT_ID, DEPT_NAME, ANNUAL_BUDGET, USED_BUDGET, REMAIN_BUDGET) 
VALUES (SEQ_DEPT_TRAIN.NEXTVAL, '市场部', 75000, 0, 75000);

INSERT INTO DEPARTMENTS_TRAINING (DEPT_ID, DEPT_NAME, ANNUAL_BUDGET, USED_BUDGET, REMAIN_BUDGET) 
VALUES (SEQ_DEPT_TRAIN.NEXTVAL, '研发中心', 120000, 0, 120000);

-- =============================================
-- 插入员工数据
-- =============================================

-- 技术部员工
INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '张伟', '技术部', '前端工程师', 'zhangwei@company.com', '13800000101', DATE '2021-03-01', '在职', SYSDATE);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '王芳', '技术部', '后端工程师', 'wangfang@company.com', '13800000102', DATE '2021-06-15', '在职', SYSDATE);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '陈明', '技术部', '全栈工程师', 'chenming@company.com', '13800000103', DATE '2020-09-01', '在职', SYSDATE);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '刘洋', '技术部', '测试工程师', 'liuyang@company.com', '13800000104', DATE '2022-02-10', '在职', SYSDATE);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '赵敏', '技术部', '运维工程师', 'zhaomin@company.com', '13800000105', DATE '2021-11-20', '在职', SYSDATE);

-- 销售部员工
INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '孙丽', '销售部', '销售代表', 'sunli@company.com', '13800000201', DATE '2020-05-10', '在职', SYSDATE);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '周涛', '销售部', '销售代表', 'zhoutao@company.com', '13800000202', DATE '2021-08-18', '在职', SYSDATE);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '吴迪', '销售部', '大客户经理', 'wudi@company.com', '13800000203', DATE '2019-11-01', '在职', SYSDATE);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '郑爽', '销售部', '销售助理', 'zhengshuang@company.com', '13800000204', DATE '2022-04-05', '在职', SYSDATE);

-- 人事部员工
INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '林晨', '人事部', '招聘专员', 'linchen@company.com', '13800000301', DATE '2020-12-10', '在职', SYSDATE);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '郭静', '人事部', '培训专员', 'guojing@company.com', '13800000302', DATE '2021-07-22', '在职', SYSDATE);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '唐雅', '人事部', '薪酬专员', 'tangya@company.com', '13800000303', DATE '2022-01-15', '在职', SYSDATE);

-- 财务部员工
INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '沈梦', '财务部', '会计', 'shenmeng@company.com', '13800000401', DATE '2019-09-01', '在职', SYSDATE);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '韩雪', '财务部', '出纳', 'hanxue@company.com', '13800000402', DATE '2021-04-18', '在职', SYSDATE);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '彭浩', '财务部', '财务分析师', 'penghao@company.com', '13800000403', DATE '2020-08-20', '在职', SYSDATE);

-- 产品部员工
INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '陆瑶', '产品部', '产品经理', 'luyao@company.com', '13800000501', DATE '2019-03-10', '在职', SYSDATE);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '苏哲', '产品部', '产品助理', 'suzhe@company.com', '13800000502', DATE '2022-06-01', '在职', SYSDATE);

-- 市场部员工
INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '高翔', '市场部', '市场专员', 'gaoxiang@company.com', '13800000601', DATE '2020-10-15', '在职', SYSDATE);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '蔡琴', '市场部', '品牌策划', 'caiqin@company.com', '13800000602', DATE '2021-12-01', '在职', SYSDATE);

-- 研发中心员工
INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '许杰', '研发中心', '算法工程师', 'xujie@company.com', '13800000701', DATE '2020-07-01', '在职', SYSDATE);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '何璐', '研发中心', '数据分析师', 'helu@company.com', '13800000702', DATE '2021-09-15', '在职', SYSDATE);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE, STATUS, CREATED_DATE) 
VALUES (SEQ_EMP.NEXTVAL, '宋阳', '研发中心', '研发工程师', 'songyang@company.com', '13800000703', DATE '2022-03-20', '在职', SYSDATE);

COMMIT;

-- =============================================
-- 验证插入结果
-- =============================================

-- 查看所有部门
SELECT * FROM DEPARTMENTS_TRAINING;

-- 查看所有员工（按部门分组）
SELECT DEPT_NAME, COUNT(*) AS EMP_COUNT 
FROM EMPLOYEES 
WHERE STATUS = '在职'
GROUP BY DEPT_NAME
ORDER BY DEPT_NAME;

-- 查看所有员工列表
SELECT EMP_ID, EMP_NAME, DEPT_NAME, POSITION, EMAIL, PHONE, HIRE_DATE
FROM EMPLOYEES 
WHERE STATUS = '在职'
ORDER BY DEPT_NAME, EMP_ID;