-- =============================================
-- 企业内部培训管理系统
-- 数据库: Oracle
-- =============================================

-- 1. 员工表
CREATE TABLE EMPLOYEES (
    EMP_ID      NUMBER PRIMARY KEY,
    EMP_NAME    VARCHAR2(50) NOT NULL,
    DEPT_NAME   VARCHAR2(100),      -- 部门名称
    POSITION    VARCHAR2(50),       -- 职位
    EMAIL       VARCHAR2(100),
    PHONE       VARCHAR2(20),
    HIRE_DATE   DATE,
    STATUS      VARCHAR2(20) DEFAULT '在职',  -- 在职/离职
    CREATED_DATE DATE DEFAULT SYSDATE
);

-- 2. 部门表（用于预算管理）
CREATE TABLE DEPARTMENTS_TRAINING (
    DEPT_ID      NUMBER PRIMARY KEY,
    DEPT_NAME    VARCHAR2(100) NOT NULL,
    ANNUAL_BUDGET NUMBER(12,2),     -- 年度培训预算
    USED_BUDGET  NUMBER(12,2) DEFAULT 0,  -- 已使用预算
    REMAIN_BUDGET NUMBER(12,2)           -- 剩余预算
);

-- 3. 讲师表
CREATE TABLE TRAINERS (
    TRAINER_ID   NUMBER PRIMARY KEY,
    TRAINER_NAME VARCHAR2(50) NOT NULL,
    TITLE        VARCHAR2(50),       -- 职称
    COMPANY      VARCHAR2(100),      -- 所属公司
    PHONE        VARCHAR2(20),
    EMAIL        VARCHAR2(100),
    STAR_LEVEL   NUMBER(1) DEFAULT 3, -- 星级 1-5
    IS_INTERNAL  VARCHAR2(10) DEFAULT '是', -- 是否内部讲师
    CREATED_DATE DATE DEFAULT SYSDATE
);

-- 4. 培训课程表
CREATE TABLE TRAINING_COURSES (
    COURSE_ID     NUMBER PRIMARY KEY,
    COURSE_NAME   VARCHAR2(200) NOT NULL,
    COURSE_TYPE   VARCHAR2(50),       -- 技能类/管理类/安全类
    DURATION      NUMBER,             -- 学时
    TRAINER_ID    NUMBER,
    MAX_STUDENTS  NUMBER,             -- 最大人数
    START_TIME    DATE,               -- 开始时间
    END_TIME      DATE,               -- 结束时间
    LOCATION      VARCHAR2(100),      -- 培训地点
    COURSE_STATUS VARCHAR2(20) DEFAULT '草稿', -- 草稿/发布/关闭
    BUDGET_AMOUNT NUMBER(10,2),       -- 预算金额
    DEPT_ID       NUMBER,             -- 主办部门
    PRE_TEST_URL  VARCHAR2(500),      -- 训前测试链接
    POST_TEST_URL VARCHAR2(500),      -- 训后测试链接
    MATERIAL_URL  VARCHAR2(500),      -- 课件资料链接
    CREATED_DATE  DATE DEFAULT SYSDATE,
    CONSTRAINT FK_COURSE_TRAINER FOREIGN KEY (TRAINER_ID) REFERENCES TRAINERS(TRAINER_ID),
    CONSTRAINT FK_COURSE_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS_TRAINING(DEPT_ID)
);

-- 5. 培训需求申请表
CREATE TABLE TRAINING_REQUESTS (
    REQUEST_ID    NUMBER PRIMARY KEY,
    EMP_ID        NUMBER,
    COURSE_ID     NUMBER,
    REASON        VARCHAR2(500),      -- 申请理由
    STATUS        VARCHAR2(20) DEFAULT '待审批', -- 待审批/主管通过/主管驳回/HR备案完成
    DEPT_APPROVER VARCHAR2(50),       -- 审批主管
    DEPT_APPROVE_TIME DATE,
    DEPT_APPROVE_REMARK VARCHAR2(500),
    HR_APPROVER    VARCHAR2(50),      -- HR备案人
    HR_APPROVE_TIME DATE,
    REQUEST_DATE  DATE DEFAULT SYSDATE,
    CONSTRAINT FK_REQ_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID),
    CONSTRAINT FK_REQ_COURSE FOREIGN KEY (COURSE_ID) REFERENCES TRAINING_COURSES(COURSE_ID)
);

-- 6. 培训报名表（用于冲突检测）
CREATE TABLE TRAINING_REGISTRATIONS (
    REG_ID        NUMBER PRIMARY KEY,
    EMP_ID        NUMBER,
    COURSE_ID     NUMBER,
    REG_DATE      DATE DEFAULT SYSDATE,
    STATUS        VARCHAR2(20) DEFAULT '已报名', -- 已报名/已签到/缺勤/已完成
    SIGNIN_TIME   DATE,               -- 签到时间
    ACTUAL_HOURS  NUMBER(4,1),        -- 实际获得学时
    IS_OVERTIME   VARCHAR2(10) DEFAULT '否', -- 是否超时签到
    CONSTRAINT FK_REG_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID),
    CONSTRAINT FK_REG_COURSE FOREIGN KEY (COURSE_ID) REFERENCES TRAINING_COURSES(COURSE_ID),
    CONSTRAINT UQ_REG_UNIQUE UNIQUE (EMP_ID, COURSE_ID)  -- 防止重复报名
);

-- 7. 培训签到记录表
CREATE TABLE TRAINING_ATTENDANCE (
    ATTEND_ID     NUMBER PRIMARY KEY,
    REG_ID        NUMBER,
    SIGNIN_TYPE   VARCHAR2(20),       -- 扫码签到/手动签到
    SIGNIN_TIME   DATE,
    LATENESS_MINUTES NUMBER,          -- 迟到分钟数
    DEDUCT_HOURS  NUMBER(4,1),        -- 扣减学时
    REMARK        VARCHAR2(500),
    CONSTRAINT FK_ATTEND_REG FOREIGN KEY (REG_ID) REFERENCES TRAINING_REGISTRATIONS(REG_ID)
);

-- 8. 讲师评分表（匿名评分）
CREATE TABLE TRAINER_RATINGS (
    RATING_ID     NUMBER PRIMARY KEY,
    COURSE_ID     NUMBER,
    TRAINER_ID    NUMBER,
    EMP_ID        NUMBER,
    SCORE         NUMBER(2,1),        -- 评分 1-5
    COMMENT       VARCHAR2(500),
    HR_VERIFIED   VARCHAR2(10) DEFAULT '否', -- HR是否复核
    HR_COMMENT    VARCHAR2(500),
    RATING_DATE   DATE DEFAULT SYSDATE,
    CONSTRAINT FK_RATING_COURSE FOREIGN KEY (COURSE_ID) REFERENCES TRAINING_COURSES(COURSE_ID),
    CONSTRAINT FK_RATING_TRAINER FOREIGN KEY (TRAINER_ID) REFERENCES TRAINERS(TRAINER_ID),
    CONSTRAINT FK_RATING_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID)
);

-- 9. 培训证书表
CREATE TABLE TRAINING_CERTIFICATES (
    CERT_ID       NUMBER PRIMARY KEY,
    EMP_ID        NUMBER,
    COURSE_ID     NUMBER,
    CERT_CODE     VARCHAR2(50),       -- 证书编号
    ISSUE_DATE    DATE,               -- 发证日期
    EXPIRE_DATE   DATE,               -- 过期日期
    NOTIFIED      VARCHAR2(10) DEFAULT '否', -- 是否已提醒
    CONSTRAINT FK_CERT_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID),
    CONSTRAINT FK_CERT_COURSE FOREIGN KEY (COURSE_ID) REFERENCES TRAINING_COURSES(COURSE_ID)
);

-- 10. 培训效果测试表（训前训后对比）
CREATE TABLE TRAINING_TESTS (
    TEST_ID       NUMBER PRIMARY KEY,
    EMP_ID        NUMBER,
    COURSE_ID     NUMBER,
    TEST_TYPE     VARCHAR2(10),       -- PRE(训前)/POST(训后)
    SCORE         NUMBER(5,2),        -- 分数 0-100
    TEST_DATE     DATE DEFAULT SYSDATE,
    CONSTRAINT FK_TEST_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID),
    CONSTRAINT FK_TEST_COURSE FOREIGN KEY (COURSE_ID) REFERENCES TRAINING_COURSES(COURSE_ID)
);

-- 11. 黑名单表（缺勤管理）
CREATE TABLE BLACKLIST (
    BLACK_ID      NUMBER PRIMARY KEY,
    EMP_ID        NUMBER,
    REASON        VARCHAR2(500),
    START_DATE    DATE,
    END_DATE      DATE,
    STATUS        VARCHAR2(20) DEFAULT '生效中', -- 生效中/已解除
    CONSTRAINT FK_BLACK_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID)
);

-- 12. 系统角色表（RBAC）
CREATE TABLE ROLES (
    ROLE_ID       NUMBER PRIMARY KEY,
    ROLE_NAME     VARCHAR2(50) NOT NULL,  -- 员工/部门主管/HR/管理员
    PERMISSIONS   VARCHAR2(2000)         -- 权限列表JSON
);

-- 13. 用户角色关联表
CREATE TABLE USER_ROLES (
    USER_ROLE_ID  NUMBER PRIMARY KEY,
    EMP_ID        NUMBER,
    ROLE_ID       NUMBER,
    CONSTRAINT FK_UR_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID),
    CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID)
);

-- =============================================
-- 创建序列
-- =============================================

CREATE SEQUENCE SEQ_EMP START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DEPT_TRAIN START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRAINER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COURSE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REQUEST START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ATTEND START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RATING START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CERT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TEST START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BLACK START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ROLE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USER_ROLE START WITH 1 INCREMENT BY 1;

-- =============================================
-- 插入测试数据
-- =============================================

-- 插入部门预算
INSERT INTO DEPARTMENTS_TRAINING VALUES (SEQ_DEPT_TRAIN.NEXTVAL, '技术部', 100000, 0, 100000);
INSERT INTO DEPARTMENTS_TRAINING VALUES (SEQ_DEPT_TRAIN.NEXTVAL, '销售部', 80000, 0, 80000);
INSERT INTO DEPARTMENTS_TRAINING VALUES (SEQ_DEPT_TRAIN.NEXTVAL, '人事部', 50000, 0, 50000);

-- 插入员工
INSERT INTO EMPLOYEES VALUES (SEQ_EMP.NEXTVAL, '张三', '技术部', '工程师', 'zhangsan@company.com', '13800000001', DATE '2020-01-01', '在职', SYSDATE);
INSERT INTO EMPLOYEES VALUES (SEQ_EMP.NEXTVAL, '李四', '技术部', '高级工程师', 'lisi@company.com', '13800000002', DATE '2018-03-15', '在职', SYSDATE);
INSERT INTO EMPLOYEES VALUES (SEQ_EMP.NEXTVAL, '王五', '销售部', '销售经理', 'wangwu@company.com', '13800000003', DATE '2019-06-20', '在职', SYSDATE);
INSERT INTO EMPLOYEES VALUES (SEQ_EMP.NEXTVAL, '赵六', '人事部', 'HR专员', 'zhaoliu@company.com', '13800000004', DATE '2021-02-10', '在职', SYSDATE);

-- 插入讲师
INSERT INTO TRAINERS VALUES (SEQ_TRAINER.NEXTVAL, '王教授', '资深培训师', '培训机构', '13900000001', 'wang@trainer.com', 5, '否', SYSDATE);
INSERT INTO TRAINERS VALUES (SEQ_TRAINER.NEXTVAL, '李经理', '内训师', '技术部', '13900000002', 'li@company.com', 4, '是', SYSDATE);

-- 插入培训课程
INSERT INTO TRAINING_COURSES VALUES (SEQ_COURSE.NEXTVAL, 'Python高级编程', '技能类', 16, 1, 30, 
    TO_DATE('2026-05-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
    TO_DATE('2026-05-12 17:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
    '培训中心201', '发布', 20000, 1, NULL, NULL, NULL, SYSDATE);

INSERT INTO TRAINING_COURSES VALUES (SEQ_COURSE.NEXTVAL, '销售技巧培训', '管理类', 8, 1, 20,
    TO_DATE('2026-05-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE('2026-05-15 17:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    '培训中心101', '发布', 10000, 2, NULL, NULL, NULL, SYSDATE);

COMMIT;

-- 创建视图：培训完成率KPI
CREATE OR REPLACE VIEW V_DEPT_KPI AS
SELECT 
    D.DEPT_NAME,
    COUNT(DISTINCT E.EMP_ID) AS TOTAL_EMP,
    COUNT(DISTINCT CASE WHEN TR.STATUS = '已完成' THEN TR.EMP_ID END) AS COMPLETED_EMP,
    ROUND(COUNT(DISTINCT CASE WHEN TR.STATUS = '已完成' THEN TR.EMP_ID END) * 100.0 / COUNT(DISTINCT E.EMP_ID), 2) AS COMPLETION_RATE
FROM DEPARTMENTS_TRAINING D
LEFT JOIN EMPLOYEES E ON D.DEPT_NAME = E.DEPT_NAME
LEFT JOIN TRAINING_REGISTRATIONS TR ON E.EMP_ID = TR.EMP_ID
GROUP BY D.DEPT_NAME;

-- 创建视图：预算使用情况
CREATE OR REPLACE VIEW V_BUDGET_USAGE AS
SELECT 
    DEPT_NAME,
    ANNUAL_BUDGET,
    USED_BUDGET,
    REMAIN_BUDGET,
    ROUND(USED_BUDGET * 100.0 / ANNUAL_BUDGET, 2) AS USAGE_RATE
FROM DEPARTMENTS_TRAINING;

SELECT '✅ 培训管理系统数据库创建成功！' AS RESULT FROM DUAL;